/* Admin presentation only. Existing task mutations and permission checks remain authoritative. */
(function(){
'use strict';
const tx=(ar,en)=>L==='ar'?ar:en, e=v=>AdvaconUI.escape(String(v??''));
let detail=null;
window.adminCloseDetail=()=>detail?.close();
const work={stage:'all',layout:'table',section:'tasks',q:'',project:'',assignee:'',status:'',page:1};
const stages=()=>[['all',tx('الكل','All')],['incoming',tx('جديدة','New')],['open',tx('قيد المعالجة','In progress')],['pending',tx('بانتظار التأكيد','Awaiting confirmation')],['complete',tx('مكتملة','Completed')],['cancelled',tx('ملغاة / مرفوضة','Cancelled / declined')],['overdue',tx('متأخرة','Overdue')]];
window.adminTaskStage=r=>isAdminArchived(r)?'cancelled':r.effStatus==='Complete'?'complete':r.pendingConfirm?'pending':!r.accepted?'incoming':'open';
const matches=(r,key)=>key==='all'||(key==='overdue'?adminTaskStage(r)==='open'&&r.effStatus==='Overdue':adminTaskStage(r)===key);
window.adminWorkRows=()=>byNumberDesc(state.requests.map(calc).filter(r=>matches(r,work.stage)&&(!work.status||r.effStatus===work.status)&&(!work.project||r.project===work.project)&&(!work.assignee||r.assignedTo===work.assignee)&&[r.title,r.requestedBy,r.assignedTo,r.notes,fmtID(r.id)].join(' ').toLowerCase().includes(work.q.trim().toLowerCase())));
function workHash(){const q=new URLSearchParams({stage:work.stage,view:work.layout,section:work.section});if(work.status)q.set('status',work.status);if(work.project)q.set('project',work.project);if(work.assignee)q.set('assignee',work.assignee);if(work.page>1)q.set('page',work.page);return 'manage?'+q;}
window.adminResolveRoute=function(raw){const [route,query='']=raw.split('?'),p=new URLSearchParams(query);if(['manage','all','archive','open'].includes(route)){work.stage=route==='archive'?'cancelled':route==='open'?'open':p.get('stage')||'all';if(!stages().some(x=>x[0]===work.stage))work.stage='all';work.layout=p.get('view')==='board'?'board':'table';work.section=p.get('section')==='period'?'period':'tasks';work.status=p.get('status')||'';work.project=p.get('project')||'';work.assignee=p.get('assignee')||'';work.page=Math.max(1,Number(p.get('page'))||1);return 'manage';}return route;};
window.adminSetWork=function(key,value){work[key]=value;if(key!=='page')work.page=1;history.replaceState(history.state,'','#'+workHash());render();};
window.adminQueue=function(key){if(state.role!=='admin')return;work.q='';go('manage?stage='+encodeURIComponent(key));};
const taskLink=(r)=>`<button class="ad-title-button" data-request-id="${Number(r.id)}" onclick="adminDetail(${Number(r.id)})">${e(r.title)}</button>`;
window.adminTaskLink=taskLink;
window.adminTeamTabs=()=>`<div class="ad-tabs"><button aria-selected="${state.route==='techtasks'}" onclick="go('techtasks')">${tx('مهام الفريق','Team workload')}</button><button aria-selected="${state.route==='staffdir'}" onclick="go('staffdir')">${tx('الموظفون','Staff directory')}</button></div>`;
function resultHTML(){const all=adminWorkRows(),max=Math.max(1,Math.ceil(all.length/40));work.page=Math.min(work.page,max);const rows=all.slice((work.page-1)*40,work.page*40),labels=Object.fromEntries(stages());const status=r=>`<span class="count-chip">${e(labels[adminTaskStage(r)])}</span>`;
 const cards=list=>list.map(r=>`<article class="mcard"><div class="mc-top"><span class="mc-id">${e(fmtID(r.id))}</span>${status(r)}</div><div class="mc-title">${taskLink(r)}</div><p>${e(r.project||'—')} · ${e(r.assignedTo||tx('غير مسند','Unassigned'))}</p>${r.effStatus==='Overdue'&&adminTaskStage(r)==='open'?`<p class="ad-overdue">${tx('متأخرة','Overdue')}</p>`:''}<div class="mc-acts"><button class="btn sec" onclick="adminDetail(${Number(r.id)})">${tx('التفاصيل والإجراءات','Details & actions')}</button></div></article>`).join('');
 const table=`<div class="tbl-wrap"><table class="tbl"><thead><tr>${[tx('رقم الطلب','Request ID'),tx('الطلب','Request'),tx('المشروع','Project'),tx('الفني','Technician'),tx('المرحلة','Stage'),tx('الاستحقاق','Due')].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${e(fmtID(r.id))}</td><td>${taskLink(r)}</td><td>${e(r.project||'—')}</td><td>${e(r.assignedTo||'—')}</td><td>${status(r)}</td><td>${e(r.due||'—')}</td></tr>`).join('')}</tbody></table></div>`;
 const board=`<div class="ad-work-board">${stages().filter(([key])=>!['all','overdue'].includes(key)).map(([key,label])=>{const items=rows.filter(r=>adminTaskStage(r)===key);return items.length?`<section class="mcol"><h3 class="mcol-head">${label} · ${items.length}</h3>${cards(items)}</section>`:'';}).join('')}</div>`;
 return `<p class="ad-muted" role="status">${all.length} ${tx('طلب مطابق','matching requests')} · ${tx('صفحة','Page')} ${work.page}/${max}</p>`+(rows.length?(work.layout==='board'?board:table):`<div class="empty">${tx('لا توجد طلبات تطابق الفلاتر','No requests match these filters')}</div>`)+`<div class="btnrow"><button class="btn sec" ${work.page<=1?'disabled':''} onclick="adminSetWork('page',${work.page-1})">${tx('السابق','Previous')}</button><button class="btn sec" ${work.page>=max?'disabled':''} onclick="adminSetWork('page',${work.page+1})">${tx('التالي','Next')}</button></div>`;
}
window.adminWorkSearch=function(input){work.q=input.value;work.page=1;const el=document.getElementById('ad-work-results');el.innerHTML=resultHTML();AdvaconUI.enhance(el);};
window.adminRequestTabs=function(){return `<div class="ad-tabs">${[['manage',tx('الطلبات','Requests')],['manage?section=period',tx('المهام الدورية','Recurring templates')],['media',tx('الصور والملفات','Images & files')]].map(([route,label])=>`<button onclick="go('${route}')" aria-selected="${route==='media'?state.route==='media':route.includes('period')?state.route==='manage'&&work.section==='period':state.route==='manage'&&work.section==='tasks'}">${label}</button>`).join('')}</div>`;};
window.adminWorkView=function(){const header=`<div class="phead phead-row"><h1>${tx('الطلبات','Requests')}</h1><button class="btn" onclick="openAddTask()">＋ ${tx('إضافة طلب','Add request')}</button></div>`+adminRequestTabs();if(work.section==='period')return header+viewPeriodTasks();const rows=state.requests.map(calc);const options=(arr,value)=>arr.map(x=>`<option value="${e(x)}" ${value===x?'selected':''}>${e(x)}</option>`).join('');return header+`<div class="ad-tabs ad-work-stages">${stages().map(([key,label])=>`<button aria-selected="${work.stage===key}" onclick="adminSetWork('stage','${key}')">${label} <b>${rows.filter(r=>matches(r,key)).length}</b></button>`).join('')}</div><p class="ad-muted">${tx('المتأخرة فلتر ضمن قيد المعالجة؛ لا تُجمع مع المراحل. الأعداد لكل الطلبات، والنتائج أدناه حسب البحث.','Overdue is a subset of in progress, not an additional stage. Stage counts cover all requests; results below follow your filters.')}</p><div class="filterbar"><input type="search" aria-label="${tx('بحث الطلبات','Search requests')}" placeholder="${tx('رقم الطلب أو العنوان أو الفني','Request ID, title or technician')}" value="${e(work.q)}" oninput="adminWorkSearch(this)"><select aria-label="${tx('المشروع','Project')}" onchange="adminSetWork('project',this.value)"><option value="">${tx('كل المشاريع','All projects')}</option>${options(state.lists.projects,work.project)}</select><select aria-label="${tx('الفني','Technician')}" onchange="adminSetWork('assignee',this.value)"><option value="">${tx('كل الفنيين','All technicians')}</option>${options(filterStaffNames(),work.assignee)}</select><select aria-label="${tx('حالة التنفيذ','Execution status')}" onchange="adminSetWork('status',this.value)"><option value="">${tx('كل حالات التنفيذ','All execution statuses')}</option>${options(state.lists.statuses,work.status)}</select><select aria-label="${tx('طريقة العرض','View')}" onchange="adminSetWork('layout',this.value)"><option value="table" ${work.layout==='table'?'selected':''}>${tx('جدول','Table')}</option><option value="board" ${work.layout==='board'?'selected':''}>${tx('لوحة','Board')}</option></select><button class="btn sec" onclick="exportExcel('work')">${tx('تصدير النتائج','Export results')}</button></div><div id="ad-work-results">${resultHTML()}</div>`;};
window.adminHome=function(){
 const rows=state.requests.map(calc),incoming=rows.filter(r=>matches(r,'incoming')),pending=rows.filter(r=>matches(r,'pending')),overdue=rows.filter(r=>matches(r,'overdue')),working=rows.filter(r=>matches(r,'open'));
 const metric=(title,n,key,kind='')=>`<button class="ad-metric ${kind}" onclick="adminQueue('${key}')"><span>${title}</span><strong>${n}</strong><small>${tx('عرض الطلبات ←','View requests →')}</small></button>`;
 return `<header class="ad-welcome"><div><span class="eyebrow">ADVACON / ${tx('الإدارة','ADMINISTRATION')}</span><h1>${tx('متابعة العمل تبدأ من هنا','Your work, at a glance')}</h1><p>${tx('الطلبات التي تحتاج قرارك، ومتابعة سير العمل.','Review requests that need a decision and follow work in progress.')}</p></div><button class="btn" onclick="openAddTask()">＋ ${tx('إضافة طلب','Add request')}</button></header>
 <div class="ad-metrics">${metric(tx('طلبات جديدة','New requests'),incoming.length,'incoming')}${metric(tx('بانتظار تأكيدك','Awaiting confirmation'),pending.length,'pending')}${metric(tx('مهام متأخرة','Overdue tasks'),overdue.length,'overdue','ad-warn')}${metric(tx('مهام مفتوحة','Open tasks'),working.length,'open')}</div>
 <div class="ad-home-grid"><section class="ad-surface"><div class="ad-section-head"><div><h2>${tx('أولوية المتابعة','Follow up first')}</h2><p>${tx('بانتظار التأكيد، ثم المتأخرة، ثم الجديدة','Awaiting confirmation, then overdue, then new')}</p></div><button class="btn sec" onclick="go('manage')">${tx('كل الطلبات','Manage requests')}</button></div><div id="ad-followup">${homeRows([...new Map([...pending,...overdue,...incoming].map(r=>[r.id,r])).values()].slice(0,8))}</div></section>
 <aside class="ad-surface"><h2>${tx('مساحات العمل','Workspaces')}</h2><p class="ad-muted">${tx('انتقل مباشرة إلى القسم المطلوب','Go directly to your workspace')}</p><div class="ad-links"><a href="/warehouse?from=admin">${tx('المستودعات','Warehouses')} <span>←</span></a><a href="/housing?from=admin">${tx('الإسكان','Housing')} <span>←</span></a><button onclick="go('techtasks')">${tx('متابعة الفريق','Team workload')} <span>←</span></button><button onclick="go('reports')">${tx('التقارير والإحصاءات','Reports & statistics')} <span>←</span></button></div></aside></div><div id="ad-decisions"></div>`;
};
function homeRows(rows){return rows.length?rows.map(r=>`<button class="ad-request" onclick="adminDetail(${Number(r.id)})"><span class="ad-request-id">${e(fmtID(r.id))}</span><span class="ad-request-title"><b>${e(r.title)}</b><small>${e(r.project||'—')} · ${e(r.assignedTo||tx('غير مسند','Unassigned'))}</small></span><span>${r.pendingConfirm?e(tx('بانتظار التأكيد','Awaiting confirmation')):stBadge(r.effStatus)}</span><span aria-hidden="true">←</span></button>`).join(''):`<div class="empty">${tx('لا توجد طلبات تحتاج متابعة عاجلة في البيانات الحالية.','No requests need urgent follow-up in the current data.')}</div>`;}
window.adminDetail=function(id,initialTab=0){
 const r=state.requests.map(calc).find(x=>x.id===id);if(!r||state.role!=='admin')return;
 if(detail)detail.close();
 const baseRoute=location.hash.split('?')[0]||'#manage',parameters=new URLSearchParams(location.hash.split('?')[1]||'');parameters.delete('task');parameters.delete('pane');const returnHash=baseRoute+(parameters.size?'?'+parameters:'');parameters.set('task',String(id));parameters.set('pane',String(initialTab));history.replaceState(history.state,'',baseRoute+'?'+parameters);
 const body=document.createElement('div');body.className='ad-detail';
 const tabs=document.createElement('div');tabs.className='ad-tabs';tabs.setAttribute('role','tablist');
 const panel=document.createElement('div');panel.className='ad-detail-content';panel.setAttribute('role','tabpanel');
 const actionbar=document.createElement('div');actionbar.className='ad-detail-actions';
 const add=(label,fn)=>{const b=document.createElement('button');b.className='btn sec';b.textContent=label;b.onclick=()=>{detail.close();detail=null;fn();};actionbar.append(b);};
 if(isIncoming(r)){add(tx('قبول الطلب','Accept request'),()=>acceptReq(id));add(tx('رفض الطلب','Decline request'),()=>askReject(id));}
 else if(r.pendingConfirm&&!isArchived(r)){add(tx('تأكيد الإنجاز','Confirm completion'),()=>confirmStaffDone(id));add(tx('إرجاع للفني','Return to technician'),()=>returnStaffTask(id));add(tx('تعديل إثبات الإنجاز','Edit completion evidence'),()=>openCloseoutEdit(id));}
 else if(isOpen(r)){add(tx('إغلاق المهمة','Close task'),()=>askClose(id));}
 add(tx('تعديل وإسناد','Edit & assign'),()=>openEdit(id));
 if(isAdminArchived(r))add(tx('استعادة الطلب','Restore request'),()=>restoreTask(id));
 if(r.effStatus==='Complete')add(tx('إعادة فتح المهمة','Reopen task'),()=>reopenTask(id));
 if(isAccepted(r)&&!r.pendingConfirm&&r.effStatus!=='Complete'){add(tx('إرجاع إلى القبول','Return to acceptance'),()=>returnToAcceptance(id));if(['On Hold','Needs Review','Needs Update'].includes(r.status))add(tx('إرجاع للفني','Return to technician'),()=>returnToTech(id));}
 const field=(label,v)=>`<div><dt>${e(label)}</dt><dd>${e(v||'—')}</dd></div>`;
 const sections=[
 [tx('التفاصيل','Details'),()=>`<dl class="ad-detail-fields">${field(tx('العنوان','Title'),r.title)}${field(tx('المشروع','Project'),r.project)}${field(tx('الفني','Technician'),r.assignedTo)}${field(tx('مقدم الطلب','Requested by'),r.requestedBy)}${field(tx('الهاتف','Phone'),r.phone)}${field(tx('الأولوية','Priority'),dispPri(r.priority))}${field(tx('موعد الاستحقاق','Due date'),r.due)}${field(tx('ملاحظات','Notes'),r.notes)}</dl>`],
 [tx('الصور والملفات','Images & files'),()=>{const a=weAtt(r);const imgs=(list)=>list.map(url=>{const safe=AdvaconExperience.safeURL(url);return safe?`<a href="${e(safe)}" target="_blank" rel="noopener"><img src="${e(safe)}" alt="${e(tx('مرفق الطلب','Request attachment'))}" loading="lazy"></a>`:'';}).join('');const docs=(list)=>list.map(f=>{const safe=AdvaconExperience.safeURL(f.url);return safe?`<a class="btn sec" href="${e(safe)}" target="_blank" rel="noopener">${e(f.name||tx('مستند','Document'))}</a>`:'';}).join('');return `<h3>${tx('مرفقات البلاغ','Request attachments')}</h3><div class="ad-images">${imgs(a.ci)}</div>${docs(a.cd)}<h3>${tx('إثبات الإنجاز','Completion evidence')}</h3><div class="ad-images">${imgs(a.pi)}</div>${docs(a.pd)}<p>${e(r.closeoutNote||'')}</p>${!a.ci.length&&!a.pi.length&&!a.cd.length&&!a.pd.length?`<p class="empty">${tx('لا توجد مرفقات','No attachments')}</p>`:''}`;}],
 [tx('المواد','Materials'),()=>{const badge=state.mrBadges?.[String(id)];if(!badge)return `<p>${tx('لا يوجد طلب مواد متاح في البيانات الحالية.','No material request is available in the current data.')}</p>`;const status={pending:tx('بانتظار التجهيز','Pending preparation'),allocated:tx('مجهّز للاستلام','Ready for collection'),issued:tx('مصروف','Issued'),rejected:tx('مرفوض','Rejected'),cancelled:tx('ملغى','Cancelled')};return `<dl class="ad-detail-fields">${field(tx('حالة المواد','Material status'),status[badge.status]||badge.status)}${field(tx('عدد الأصناف','Line count'),String(badge.lines_count??'—'))}</dl><div class="btnrow">${mrProcBtn(id)}</div>`;}],
 [tx('سجل الحركة','Timeline'),()=>`<ol class="ad-timeline">${[[tx('استقبال الطلب','Received'),r.receivedAt||r.received],[tx('بدء العمل','Started'),r.startedAt],[tx('أُرسل للتأكيد','Submitted for confirmation'),r.pendingConfirmAt],[tx('اكتمال / إغلاق','Completed / closed'),r.confirmedAt||r.closed],[tx('رفض / إلغاء','Declined / cancelled'),r.rejectedAt]].filter(x=>x[1]).map(x=>`<li><b>${e(x[0])}</b><span>${e(wpDate(x[1]))}</span></li>`).join('')}</ol>`]
 ];
 sections.forEach(([label,content],i)=>{const b=document.createElement('button');b.textContent=label;b.type='button';b.setAttribute('role','tab');b.onclick=()=>{[...tabs.children].forEach(x=>x.setAttribute('aria-selected',String(x===b)));panel.innerHTML=content();const params=new URLSearchParams(location.hash.split('?')[1]||'');if(params.get('task')===String(id)){params.set('pane',String(i));history.replaceState(history.state,'',location.hash.split('?')[0]+'?'+params);}AdvaconUI.enhance(panel);};tabs.append(b);if(!i)b.click();});
 tabs.addEventListener('keydown',ev=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();const buttons=[...tabs.children],i=buttons.indexOf(document.activeElement),next=ev.key==='Home'?0:ev.key==='End'?buttons.length-1:(i+(ev.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();buttons[next].click();});
 panel.addEventListener('click',event=>{if(event.target.closest('button[onclick]')&&detail){detail.close();detail=null;}},true);
 tabs.children[initialTab]?.click();
 body.append(tabs,panel,actionbar);detail=AdvaconUI.modal({title:fmtID(id)+' · '+r.title,body,footer:false,onClose:()=>{detail=null;if(new URLSearchParams(location.hash.split('?')[1]||'').get('task')===String(id))history.replaceState(history.state,'',returnHash);}});detail.modal.classList.add('ad-detail-modal');
};
function decorate(){
 const admin=state.role==='admin';document.body.classList.toggle('ad-admin',admin);if(!admin)return;
 const activeRoute=['all','archive','open','media'].includes(state.route)?'manage':state.route==='staffdir'?'techtasks':state.route;document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick')===`go('${activeRoute}')`));
 const rename=(key,label)=>{const button=document.querySelector(`.side-nav [onclick="go('${key}')"]`);if(button?.children[1])button.children[1].textContent=label;};rename('dashboard',tx('الرئيسية','Home'));rename('reports',tx('التقارير والإحصاءات','Reports & statistics'));
 rename('manage',tx('الطلبات','Requests'));rename('techtasks',tx('الفريق','Team'));
 const statuses={'Overdue':'متأخرة','Not Started':'لم تبدأ','In Progress':'قيد التنفيذ','Complete':'مكتملة','Cancelled':'ملغاة','On Hold':'معلّقة','Needs Review':'بحاجة مراجعة','Needs Update':'بحاجة تحديث'};
 if(L==='ar')document.querySelectorAll('#view .st').forEach(b=>{if(statuses[b.textContent])b.textContent=statuses[b.textContent];});
 const nav=document.querySelector('.side-nav');if(nav){const groups=[['dashboard',tx('مساحة العمل','WORKSPACE')],['techtasks',tx('الفريق والأصول','TEAM & ASSETS')],['reports',tx('السجلات والإعدادات','RECORDS & SETTINGS')]];groups.forEach(([key,label])=>{const b=nav.querySelector(`[onclick="go('${key}')"]`);if(b&&!b.previousElementSibling?.classList.contains('ad-nav-label')){const title=document.createElement('div');title.className='ad-nav-label';title.textContent=label;b.before(title);}});nav.querySelectorAll('button').forEach(b=>{if(b.classList.contains('active'))b.setAttribute('aria-current','page');});}
 if(state.route==='dashboard'){const target=document.getElementById('ad-decisions');if(target)renderDecisionSummary(target);}
 const query=new URLSearchParams(location.hash.split('?')[1]||'');if(!detail&&query.has('task')){const id=Number(query.get('task'));if(Number.isSafeInteger(id))adminDetail(id,Math.max(0,Math.min(3,Number(query.get('pane'))||0)));}

}
window.adminDecorate=decorate;
window.addEventListener('popstate',()=>{if(state.role==='admin'){const target=location.hash;adminCloseDetail();history.replaceState(history.state,'',target);state.route=adminResolveRoute(target.slice(1)||'dashboard');render();}});
document.addEventListener('DOMContentLoaded',decorate);
})();

