(function(){'use strict';const root=document.querySelector('#body'),config=window.vehicleIntakeConfig;let session='',vehicles=[],employee='';
function n(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e;}function label(text,i){const l=n('label',text);l.append(i);return l;}
async function call(name,args){const r=await fetch(config.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+config.key,'Content-Type':'application/json'},body:JSON.stringify(args)});const data=await r.json();if(!r.ok||!data.ok)throw Error(data.error||data.message||'تعذر الحفظ');return data;}
const rpc=(vehicle,payload)=>call('advacon_vehicle_intake_shared',{p_session:session,p_vehicle_id:vehicle||null,p_payload:payload||null});
const messages={identity_expired:'انتهت جلسة التعبئة. افتح الرابط وتحقق من الإقامة مجددًا.',invalid_iqama:'أدخل رقم إقامة صحيحًا من عشرة أرقام.',employee_not_registered:'الإقامة غير مسجلة أو الموظف غير نشط. تواصل مع الإدارة.',lookup_rate_limited:'محاولات كثيرة. انتظر قليلًا ثم حاول مجددًا.',employee_phone_missing:'راجع الإدارة لاستكمال بيانات الموظف.',vehicle_not_assigned:'السيارة لم تعد مسندة لك. تواصل مع الإدارة.',complete_all_services:'أكمل حالة كل خدمة.',service_odometer_above_current:'عداد الصيانة السابقة أعلى من العداد الحالي.',odometer_below_recorded:'العداد أقل من القراءة المسجلة. تحقق من القراءة أو راجع الإدارة.',invalid_current_reading:'تحقق من قراءة العداد وتاريخها.',warranty_date_required:'أدخل تاريخ نهاية ضمان البطارية.',inspection_expiry_required:'أدخل تاريخ انتهاء الفحص.',service_date_required:'راجع تواريخ الصيانة؛ لا تقبل تواريخ مستقبلية.'};
function error(e){return messages[Object.keys(messages).find(k=>e.message.includes(k))]||'تعذر استكمال العملية. تحقق من البيانات أو تواصل مع الإدارة.';}
function login(){session='';root.replaceChildren();const f=n('form'),i=n('input'),b=n('button','دخول'),msg=n('p');b.type='submit';i.inputMode='numeric';i.required=true;i.maxLength=10;i.autocomplete='off';f.append(label('رقم الإقامة',i),b,msg);root.append(f);f.onsubmit=async e=>{e.preventDefault();const iqama=i.value.trim().replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c));b.disabled=true;try{const identity=await call('advacon_visitor_identify',{p_iqama:iqama});const opened=await call('advacon_vehicle_intake_open',{p_ticket:identity.ticket});session=opened.session;await refresh();}catch(e){msg.textContent=error(e);}finally{b.disabled=false;}};}
async function refresh(){const d=await rpc();vehicles=d.vehicles;employee=d.employee;choose();}
function choose(){root.replaceChildren(n('h2','السلام عليكم، '+employee),n('p','الرجاء تحديث بيانات سيارتك.'));if(!vehicles.length)root.append(n('p','لا توجد سيارة مرتبطة بملفك حاليًا. يرجى مراجعة الإدارة.'));for(const v of vehicles){const b=n('button',(v.plate||'لوحة غير مسجلة')+' — '+(v.description||'')+(v.submitted?' · تم تحديث البيانات':''));b.type='button';b.disabled=v.submitted;b.onclick=()=>form(v);root.append(b);}if(vehicles.length&&vehicles.every(v=>v.submitted))root.append(n('p','اكتملت بيانات سياراتك. شكرًا لك.'));const exit=n('button','خروج');exit.type='button';exit.onclick=login;root.append(exit);}
function form(v){root.replaceChildren(n('h2','السلام عليكم، '+employee),n('p',(v.plate||'بدون لوحة')+' — '+(v.description||'')),n('p','الرجاء تحديث بيانات سيارتك. بعد الحفظ، لا يمكن إعادة التعبئة إلا من خلال الإدارة.'));const f=n('form'),km=n('input'),image=n('input'),submit=n('button','حفظ بيانات السيارة'),msg=n('p');submit.type='submit';km.type='number';km.min=0;km.max=10000000;km.required=true;image.type='file';image.accept='image/jpeg,image/png';image.capture='environment';image.required=true;f.append(label('الممشى الحالي بالكيلومترات',km),label('صورة واضحة للعداد — JPG أو PNG',image));const get=AdvaconVehicleServices.formEntries(f);f.append(submit,msg);const back=n('button','العودة للسيارات');back.type='button';back.onclick=choose;root.append(back,f);f.onsubmit=async e=>{e.preventDefault();submit.disabled=true;back.disabled=true;try{const data={odometer:km.value,observed_on:new Date(Date.now()+10800000).toISOString().slice(0,10),image:await AdvaconVehicleServices.photo(image.files[0]),entries:get()};await rpc(v.id,data);v.submitted=true;await refresh();}catch(e){msg.textContent=error(e);msg.scrollIntoView({block:'center'});}finally{submit.disabled=false;back.disabled=false;}};}
login();})();
