(function(){'use strict';const root=document.querySelector('#body'),token=location.hash.slice(1),config=window.vehicleIntakeConfig;let iqama='',vehicles=[];
function n(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e;}function label(text,i){const l=n('label',text);l.append(i);return l;}
async function rpc(vehicle,payload){const r=await fetch(config.url+'/rest/v1/rpc/advacon_vehicle_intake',{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+config.key,'Content-Type':'application/json'},body:JSON.stringify({p_token:token,p_iqama:iqama,p_vehicle_id:vehicle||null,p_payload:payload||null})});const data=await r.json();if(!r.ok||!data.ok)throw Error(data.error||data.message||'تعذر الحفظ');return data;}
const messages={identity_mismatch:'رقم الإقامة لا يطابق صاحب الرابط.',invalid_or_expired_link:'الرابط غير صالح أو انتهت مدته. اطلب رابطًا جديدًا من الإدارة.',vehicle_changed_contact_admin:'تم تحديث ملف السيارة بعد إصدار الرابط؛ تواصل مع الإدارة قبل الاستكمال.',vehicle_not_assigned:'السيارة لم تعد مسندة لك. تواصل مع الإدارة.',complete_all_services:'أكمل حالة كل خدمة.',service_odometer_above_current:'عداد الصيانة السابقة أعلى من العداد الحالي.',warranty_date_required:'أدخل تاريخ نهاية ضمان البطارية.',inspection_expiry_required:'أدخل تاريخ انتهاء الفحص.',service_date_required:'راجع تواريخ الصيانة؛ لا تقبل تواريخ مستقبلية.'};
function error(e){return messages[Object.keys(messages).find(k=>e.message.includes(k))]||e.message;}
function login(){root.replaceChildren();if(!/^[a-f0-9-]{36}$/i.test(token)){root.append(n('p','افتح رابط التعبئة الخاص بك الذي وصلك من الإدارة.'));return;}const f=n('form'),i=n('input'),b=n('button','عرض سياراتي'),msg=n('p');b.type='submit';i.inputMode='numeric';i.required=true;i.maxLength=10;f.append(label('رقم الإقامة',i),b,msg);root.append(f);f.onsubmit=async e=>{e.preventDefault();iqama=i.value.trim().replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c));b.disabled=true;try{const d=await rpc();vehicles=d.vehicles;choose(d.employee);}catch(e){msg.textContent=error(e);}finally{b.disabled=false;}};}
function choose(employee){root.replaceChildren(n('h2',employee),n('p','اختر سيارة لاستكمال بياناتها. الإرسال مرة واحدة لكل سيارة؛ التصحيح بعد ذلك من الإدارة.'));for(const v of vehicles){const b=n('button',(v.plate||'لوحة غير مسجلة')+' — '+v.description+(v.submitted?' · تم الإرسال':''));b.disabled=v.submitted;b.onclick=()=>form(v);root.append(b);}if(vehicles.every(v=>v.submitted))root.append(n('p','اكتملت بيانات سياراتك. شكرًا لك.'));}
function form(v){root.replaceChildren(n('h2',(v.plate||'بدون لوحة')+' — '+v.description),n('p','البيانات الموجودة تخص سيارتك تلقائيًا. أكمل الأقسام، ولا تدخل تاريخًا أو قراءة تقديرية. إذا تعذر توثيق خدمة، اختر استكمال الأدمن.'));const f=n('form'),km=n('input'),image=n('input'),submit=n('button','إرسال البيانات'),msg=n('p');submit.type='submit';km.type='number';km.min=0;km.max=10000000;km.required=true;image.type='file';image.accept='image/jpeg,image/png';image.capture='environment';image.required=true;f.append(label('الممشى الحالي بالكيلومترات',km),label('صورة واضحة للعداد — JPG أو PNG',image));const get=AdvaconVehicleServices.formEntries(f);f.append(submit,msg);root.append(f);f.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const data={odometer:km.value,observed_on:new Date(Date.now()+10800000).toISOString().slice(0,10),image:await AdvaconVehicleServices.photo(image.files[0]),entries:get()};await rpc(v.id,data);const d=await rpc();vehicles=d.vehicles;choose(d.employee);}catch(e){msg.textContent=error(e);msg.scrollIntoView({block:'center'});}finally{submit.disabled=false;}};}
login();})();
